--- #YAML:1.0
name:               Net-SMS-O2_DE
version:            0.05
abstract:           a module to send SMS messages using the O2 Germany web2sms! Only for Internet-Pack users with free sms.
author:
    - Stefan Profanter <profanter@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::SSLeay:  0
    Date::Format:   0
    Net::SMS::Web:  0
    Test::More:     0
    Time::Local:    0
    URI::Escape:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
